project13/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific
urlpatterns = [
    path('admin/', admin.site.urls),
    path('murali/',murali,name='murali'),
    path('meena/',meena,name='meena'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path
app_name='specific'
urlpatterns=[
    path('chandu/',chandu,name='chandu'),
    path('mouni/',mouni,name='mouni'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def murali(request):
    return render(request,'murali.html')
def meena(request):
    return render(request,'meena.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def chandu(request):
    return render(request,'chandu.html')
def mouni(request):
    return render(request,'mouni.html')
    

templates/chandu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hey mouni,today our mom is going to make parato and potato curry</h1>
        <h1>Do you know that?</h1>
        <a href="{% url 'specific:mouni' %}"><h1>mouni response</h1></a>
    </center>
</body>
</html>

templates/meena.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>yeah hi murali,so today i will try new recipie </h1>
        <h1>how about parata and potato curry</h1>
        <a href="{% url 'murali' %}"><h1> murali response</h1></a>
    </center>
</body>
</html>

templates/mouni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Yeah i know chandu ,i am also helping to mom</h1>
        <h1>its looking yummy</h1>
        <a href="{% url 'specific:chandu' %}"><h1>chandu response</h1></a>
        <a href="{% url 'meena' %}"><h1>mom response</h1></a>
    </center>
</body>
</html>

templates/murali.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi meena ,what are you making for todays food?</h1>
        <h1> can you try any new recepie please</h1>
        <a href="{% url 'meena' %}"><h1>meena response</h1></a>
        <a href="{% url 'specific:chandu' %}"><h1>chandu</h1></a>
        <a href="{% url 'specific:mouni' %}"><h1>mouni</h1></a>
    </center>
</body>
</html>